name: Atividade04

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ação pré-existente para verificar o código
    - name: Checkout repository
      uses: actions/checkout@v3

    # ação pré-existente configurar o Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    # ação personalizada instalação de dependências
    - name: Install dependencies
      run: npm install

